version: '2'
services:
  unifi:
    image: andrewglass3/unifi5
    ports:
    - "8081:8081"
    - "8080:8080"
    - "8443:8443"
    - "8843:8843"
    - "3478:3478"
    restart: always
    volumes:
            - /mnt/docker/unifi/data:/var/lib/unifi
            - /mnt/docker/unifi/logs:/var/log/unifi 
